services:
  - type: pserv
    name: sixamolp-frontend
    env: node
    plan: starter
    repo: https://github.com/xefino/sixamolp-frontend
    branch: develop
    region: singapore
    buildCommand: yarn; yarn build:dev
    startCommand: yarn start
    envVars:
      - key: REVALIDATE
        value: 60
      - key: STRAPI_URL
        sync: false
  - type: web
    name: oauth2-proxy
    env: docker
    plan: starter
    region: singapore
    envVars:
      - key: UPSTREAM
        fromService:
          name: sixamolp-frontend
          type: pserv
          property: hostport
      - key: OAUTH2_PROXY_PROVIDER
        sync: false
      - key: OAUTH2_PROXY_CLIENT_ID
        sync: false
      - key: OAUTH2_PROXY_CLIENT_SECRET
        sync: false
      - key: OAUTH2_PROXY_COOKIE_SECRET
        generateValue: true
      - key: OAUTH2_PROXY_EMAIL_DOMAINS
        value: '*'
      - key: OAUTH2_PROXY_HTTP_ADDRESS
        value: ":10000"
      - key: OAUTH2_PROXY_GITHUB_ORG
        value: "xefino"
      - key: OAUTH2_PROXY_GITHUB_USER
        value: "sixamolp-test"
